# Generated by Django 5.0.6 on 2024-06-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_block_blocked_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked_user')},
        ),
    ]
